### ISSUE TITLE
frameworkify.py: error: no such option: -f

### ISSUE THREAD

**Issue by xbelanch** [mitsuhiko/frameworkify#1]
Hi,

Thanks for share this helpful script but I have a little problem every time I run make to build the project:

```
Usage: frameworkify.py [options]
frameworkify.py: error: no such option: -f
```

I use the SDL 1.2.7  version instead of 1.3. For this reason I don't include in CMakeList.txt the find_library option. Instead of this I add the common find_package(SDL 1.2.7 REQUIRED). In this sense, I check the value ${SDL_LIBRARY}  from the script called in CMakeList.txt  and seems to be the root of the problem: 

```
/opt/local/lib/libSDLmain.a /opt/local/lib/libSDL.dylib -framework Cocoa
```

I guess that the error message (option -f) responds to the _f_ of the _-framework_  option 

Any clue?

Thanks in advance!
Xavier

**Comment by mitsuhiko** [comment]
Ah yes. cmake magic gets in the way there. Cmake abuses the library name to also include the framework option. Guess you have to filter that out then before calling into frameworkify or you get rid of that in the frameworkify script itself. It's not very big, so you should be able to customize it easily.

**Comment by mitsuhiko** [comment]
Also, the SDLmain.a will not work either, so you have to make sure you don't pass that to frameworkify.
